import "./globals.css";

import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import Logo from "@/assets/images/logo47.png";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-slate-500 p-2 px-5 flex gap-5">
          <Link href={"/"}>
            <Image src={Logo} alt="logo" width={50} height={50} />
          </Link>
          <Link href={"/dashboard"}>Dashboard</Link>
          <Link href={"/blog"}>Blog</Link>
          <Link href={"/group-layout"}>Group Layout</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
